name: fwdpy_docs

channels:
    - defaults
    - conda-forge
    - bioconda

dependencies:
    - python>=3.6
    - sphinx_rtd_theme==0.1.9
    - pybind11==2.3.0
    - gsl==2.4
    - msprime
    - openblas
    - numpy
    - pandas
    - matplotlib
    - ipython
    - cmake
    - pip:
        - cppimport
