name: Build and deploy manual

on:
  pull_request:
  push:
    branches: [main]

jobs:
  builddocs:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc]
        python-version: [3.8]
    defaults:
      run:
        shell: bash
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ secrets.FWDPY11_RECIPE_ACTIONS }}

      - name: Checkout
        uses: actions/checkout@v2

      # We install the R dependencies first
      # Later, Python dependencies will go into the same place.
      # Python will silently update dependencies if needed,
      # and they'll get cached, too.
      - name: Cache dependancies
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.local
          key: ${{ matrix.python }}-${{ hashFiles('doc/requirements.txt') }}-${{ hashFiles('requirements.txt') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install apt dependencies
        run: |
          sudo apt install --fix-missing -y libgsl-dev cmake 

      - name: Set GCC as compiler
        if: matrix.compiler == 'gcc'
        run: |
          echo "CC=gcc-9" >> $GITHUB_ENV
          echo "CXX=g++-9" >> $GITHUB_ENV

      - name: Test compiler
        if: matrix.compiler == 'gcc'
        run: |
          $CXX -v
          $CC -v

      - name: Edit PATH
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          python -m pip install --user  "pybind11[global]"
          python -m pip install --user --upgrade -r book/requirements.txt

      - name: Test that fwdpy11 is discoverable
        run: |
          python -c "import fwdpy11; print(fwdpy11.__version__)"
          python -m fwdpy11 --help

      - name: Build module
        run: |
            python3 setup.py build_ext -i

      - name: Test that C++ module is discoverable
        run: |
          python -c "import fp11recipes.freqtrackercpp"

      - name: Build the book
        working-directory: doc
        run: |
          make

      - name: Move built HTML book
        if: github.ref == 'refs/heads/main'
        working-directory: doc
        run: |
          mv _build/html book_output

      - name: Upload artifacts
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v1
        working-directory: doc
        with:
          name: book_output
          path: book_output/

  deploy:
    name: deploy
    needs: builddocs
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: book_output # optional
          # Destination path
          path: book_output # optional
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.FWDPY11_RECIPE_ACTIONS }} 
        with:
          build_dir: book_output/
